export interface VPSProvider {
  id: string;
  name: string;
  logo: string;
  priceFrom: string;
  minConfig: string;
  storageType: string;
  traffic: string;
  portSpeed: string;
  locations: string[];
  locationsCN: string[];
  routes: string[];
  tags: string[];
  website: string;
  goSlug?: string;
  latency: Record<string, { telecom: number; unicom: number; mobile: number }>;
  review: string;
  scenarios: string[];
  proxyFriendly: boolean;
  ipPolicy: string;
  virtualization: string;

    streaming: string;
}

export function bestLatency(provider: VPSProvider): { telecom: number; unicom: number; mobile: number } {
  let best = { telecom: 999, unicom: 999, mobile: 999 };
  for (const l of Object.values(provider.latency)) {
    if (l.telecom < best.telecom) best.telecom = l.telecom;
    if (l.unicom < best.unicom) best.unicom = l.unicom;
    if (l.mobile < best.mobile) best.mobile = l.mobile;
  }
  return best;
}

export interface Scenario {
  id: string;
  title: string;
  description: string;
  icon: string;
  providers: string[];
}

export const scenarios: Scenario[] = [
  {
    id: 'proxy',
    title: 'VPS 代理方案',
    description: '自建代理节点，稳定访问海外服务',
    icon: 'shield',
    providers: ['dmit', 'bandwagon', 'vps', 'gigsgigs', 'lisa'],
  },
  {
    id: 'hosting',
    title: '网站托管',
    description: 'WordPress / 静态博客 / 小型应用',
    icon: 'globe',
    providers: ['racknerd', 'cloudcone', 'hosthatch', 'buyvm', 'vultr', 'digitalocean'],
  },
  {
    id: 'dev',
    title: '开发测试',
    description: 'Docker 环境 / CI Runner / 实验机',
    icon: 'terminal',
    providers: ['vultr', 'digitalocean', 'colocrossing'],
  },
  {
    id: 'gaming',
    title: '游戏加速',
    description: '低延迟线路，适合游戏联机',
    icon: 'zap',
    providers: ['dmit', 'vps', 'gigsgigs', 'lisa'],
  },
  {
    id: 'pt',
    title: 'PT / BT 下载',
    description: '大流量不限速，适合下载场景',
    icon: 'download',
    providers: ['buyvm', 'hosthatch', 'colocrossing'],
  },
  {
    id: 'learning',
    title: '学习实验',
    description: '低价练手，学习 Linux / 网络',
    icon: 'book',
    providers: ['racknerd', 'cloudcone', 'virmach', 'yxvm'],
  }];

export const solutionPaths = [
  {
    level: 'zero',
    title: '零成本',
    subtitle: '免费方案',
    description: 'Cloudflare Tunnel / Workers 免费额度 / 公共代理',
    timeEstimate: '0 min',
    costEstimate: '¥0',
    color: 'green',
  },
  {
    level: 'starter',
    title: '入门',
    subtitle: '$2-5/月 VPS',
    description: 'RackNerd / CloudCone 等性价比机型，满足日常代理和建站',
    timeEstimate: '5 min',
    costEstimate: '¥15-35/月',
    color: 'blue',
  },
  {
    level: 'advanced',
    title: '进阶',
    subtitle: 'CN2 GIA 优化',
    description: 'DMIT / V.PS 等精品线路，电信 CN2 / 联通 9929 / 移动 CMI',
    timeEstimate: '5 min',
    costEstimate: '¥70-200/月',
    color: 'purple',
  },
  {
    level: 'selfbuild',
    title: '自建代理',
    subtitle: '一键部署脚本',
    description: 'Sing-box / Xray 全家桶，Reality + Hysteria2 混合协议',
    timeEstimate: '2 min',
    costEstimate: 'Any VPS',
    color: 'orange',
  }];

export const rankingCategories = [
  {
    id: 'value',
    title: '性价比之王',
    providers: ['racknerd', 'cloudcone', 'buyvm', 'hosthatch', 'virmach', 'colocrossing'],
  },
  {
    id: 'route',
    title: '线路最优',
    providers: ['dmit', 'vps', 'bandwagon', 'gigsgigs', 'lisa'],
  },
  {
    id: 'proxy',
    title: '代理首选',
    providers: ['dmit', 'bandwagon', 'vps', 'lisa'],
  },
  {
    id: 'beginner',
    title: '新手推荐',
    providers: ['racknerd', 'cloudcone', 'bandwagon', 'buyvm', 'virmach'],
  }];


export const providers: VPSProvider[] = [
  {
    id: 'bandwagon',
    name: 'BandwagonHost',
    logo: '/logos/bandwagon.svg',
    priceFrom: '$49.99/季',
    minConfig: '2C 1G 20G',
    storageType: 'SSD',
    traffic: '1 TB',
    portSpeed: '2.5Gbps',
    locations: ['Los Angeles', 'Tokyo', 'Amsterdam'],
    locationsCN: ['美国洛杉矶', '日本东京', '荷兰阿姆斯特丹'],
    routes: ['CN2 GIA', 'CMIN2', 'AS9929'],
    tags: ['性价比', '一键换IP'],
    website: 'https://bandwagonhost.com/',
    latency: {
      'Los Angeles': { telecom: 155, unicom: 160, mobile: 185 },
      'Tokyo': { telecom: 80, unicom: 75, mobile: 95 },
      'Amsterdam': { telecom: 220, unicom: 230, mobile: 255 },
    },
    review: '经典性价比之选，KiwiVM 面板功能丰富',
    scenarios: ['proxy', 'hosting'],
    proxyFriendly: true,
    ipPolicy: '免费更换',
    virtualization: 'KVM',
    streaming: 'Netflix, YouTube',
  },
  {
    id: 'buyvm',
    name: 'BuyVM',
    logo: '/logos/buyvm.svg',
    priceFrom: '$7/月',
    minConfig: '1C 1G 250G',
    storageType: 'HDD',
    traffic: '不限流量',
    portSpeed: '1Gbps',
    locations: ['Las Vegas', 'Piscataway', 'Luxembourg'],
    locationsCN: ['美国拉斯维加斯', '美国皮斯卡特维', '卢森堡'],
    routes: ['普通国际'],
    tags: ['不限流量', '附加存储', '稳定'],
    website: 'https://my.frantech.ca/',
    latency: {
      'Las Vegas': { telecom: 195, unicom: 188, mobile: 210 },
      'Piscataway': { telecom: 235, unicom: 228, mobile: 252 },
      'Luxembourg': { telecom: 210, unicom: 205, mobile: 230 },
    },
    review: '不限流量 + 可附加大容量存储块',
    scenarios: ['pt', 'hosting'],
    proxyFriendly: false,
    ipPolicy: '不保证',
    virtualization: 'KVM',
    streaming: '未测试',
  },
  {
    id: 'cloudcone',
    name: 'CloudCone',
    logo: '/logos/cloudcone.svg',
    priceFrom: '$2.00/月',
    minConfig: '1C 1G 14G',
    storageType: 'SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Los Angeles'],
    locationsCN: ['美国洛杉矶'],
    routes: ['普通国际'],
    tags: ['按小时计费', '低价', '灵活'],
    website: 'https://app.cloudcone.com/',
    latency: {
      'Los Angeles': { telecom: 170, unicom: 163, mobile: 188 },
    },
    review: '按小时计费，随时可销毁退款',
    scenarios: ['hosting', 'learning'],
    proxyFriendly: false,
    ipPolicy: '销毁重建',
    virtualization: 'KVM',
    streaming: '未测试',
  },
  {
    id: 'cloudsilk',
    name: 'CloudSilk',
    logo: '/logos/cloudsilk.svg',
    priceFrom: '$3/月',
    minConfig: '1C 512M 10G',
    storageType: 'SSD',
    traffic: '500 GB',
    portSpeed: '500Mbps',
    locations: ['San Jose'],
    locationsCN: ['美国圣何塞'],
    routes: ['AS9929'],
    tags: ['三网优化', '低价'],
    website: 'https://cloudsilk.io/',
    latency: {
      'San Jose': { telecom: 148, unicom: 155, mobile: 172 },
    },
    review: '白丝云，AS9929 优化线路',
    scenarios: ['proxy'],
    proxyFriendly: true,
    ipPolicy: '免费更换',
    virtualization: 'KVM',

    streaming: 'Netflix, Disney+',
  },
  {
    id: 'colocrossing',
    name: 'ColoCrossing',
    logo: '/logos/colocrossing.svg',
    priceFrom: '$4/月',
    minConfig: '1C 1G 25G',
    storageType: 'SSD',
    traffic: '20 TB',
    portSpeed: '1Gbps',
    locations: ['Los Angeles'],
    locationsCN: ['美国洛杉矶'],
    routes: ['普通国际'],
    tags: ['大带宽', '美国'],
    website: 'https://cloud.colocrossing.com/',
    latency: {
      'Los Angeles': { telecom: 168, unicom: 162, mobile: 185 },
    },
    review: '美国 VPS，性价比高',
    scenarios: ['pt', 'dev'],
    proxyFriendly: false,
    ipPolicy: '不保证',
    virtualization: 'KVM',

    streaming: '未测试',
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    logo: '/logos/digitalocean.svg',
    priceFrom: '$4/月',
    minConfig: '1C 512M 10G',
    storageType: 'NVMe SSD',
    traffic: '500 GB',
    portSpeed: '1Gbps',
    locations: ['Singapore', 'Bangalore', 'London', 'Frankfurt', 'Amsterdam', 'New York'],
    locationsCN: ['新加坡', '印度班加罗尔', '英国伦敦', '德国法兰克福', '荷兰阿姆斯特丹', '美国纽约'],
    routes: ['普通国际'],
    tags: ['大厂', '开发者友好', '生态好'],
    website: 'https://m.do.co/',
    latency: {
      'Singapore': { telecom: 88, unicom: 82, mobile: 65 },
      'Bangalore': { telecom: 128, unicom: 122, mobile: 110 },
      'London': { telecom: 195, unicom: 190, mobile: 212 },
      'Frankfurt': { telecom: 192, unicom: 185, mobile: 205 },
      'Amsterdam': { telecom: 185, unicom: 178, mobile: 200 },
      'New York': { telecom: 238, unicom: 232, mobile: 255 },
    },
    review: '老牌开发者云，文档和社区最好',
    scenarios: ['dev', 'hosting'],
    proxyFriendly: true,
    ipPolicy: '按小时计费',
    virtualization: 'KVM',

    streaming: '未测试',
  },
  {
    id: 'dmit',
    name: 'DMIT',
    logo: '/logos/dmit.svg',
    priceFrom: '$36.90/年',
    minConfig: '1C 1G 20G',
    storageType: 'SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Los Angeles', 'Hong Kong', 'Tokyo'],
    locationsCN: ['美国洛杉矶', '中国香港', '日本东京'],
    routes: ['CN2 GIA', 'CMIN2'],
    tags: ['精品线路', '低延迟'],
    website: 'https://dmit.io/',
    latency: {
      'Los Angeles': { telecom: 142, unicom: 151, mobile: 175 },
      'Hong Kong': { telecom: 35, unicom: 40, mobile: 28 },
      'Tokyo': { telecom: 55, unicom: 62, mobile: 48 },
    },
    review: 'CN2 GIA 顶级线路，延迟极低',
    scenarios: ['proxy', 'gaming'],
    proxyFriendly: true,
    ipPolicy: '免费更换',
    virtualization: 'KVM',

    streaming: 'Netflix, Disney+',
  },
  {
    id: 'gigsgigs',
    name: 'GigsGigs',
    logo: '/logos/gigsgigs.svg',
    priceFrom: '$12/月',
    minConfig: '1C 512M 20G',
    storageType: 'SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Hong Kong', 'Tokyo', 'Singapore', 'Los Angeles'],
    locationsCN: ['中国香港', '日本东京', '新加坡', '美国洛杉矶'],
    routes: ['CN2 GIA', 'CMI', 'AS9929'],
    tags: ['CN2 GIA', '亚太', '老牌'],
    website: 'https://gigsgigscloud.com/',
    latency: {
      'Hong Kong': { telecom: 36, unicom: 42, mobile: 30 },
      'Tokyo': { telecom: 58, unicom: 62, mobile: 48 },
      'Singapore': { telecom: 88, unicom: 82, mobile: 65 },
      'Los Angeles': { telecom: 148, unicom: 155, mobile: 172 },
    },
    review: '亚太精品线路老牌商家，稳定性好',
    scenarios: ['proxy', 'hosting'],
    proxyFriendly: true,
    ipPolicy: '工单申请',
    virtualization: 'KVM',

    streaming: 'Netflix, Disney+',
  },
  {
    id: 'hostdare',
    name: 'HostDare',
    logo: '/logos/hostdare.svg',
    priceFrom: '$55.99/年',
    minConfig: '1C 756M 35G',
    storageType: 'HDD',
    traffic: '500 GB',
    portSpeed: '50Mbps',
    locations: ['Los Angeles'],
    locationsCN: ['美国洛杉矶'],
    routes: ['CN2 GIA'],
    tags: ['CN2 GIA', '美西'],
    website: 'https://hostdare.com/',
    latency: {
      'Los Angeles': { telecom: 146, unicom: 152, mobile: 168 },
    },
    review: '美西 CN2 GIA 线路，入门选择',
    scenarios: ['proxy'],
    proxyFriendly: true,
    ipPolicy: '付费更换',
    virtualization: 'KVM',

    streaming: 'Netflix',
  },
  {
    id: 'hosthatch',
    name: 'HostHatch',
    logo: '/logos/hosthatch.svg',
    priceFrom: '$4/月',
    minConfig: '1C 2G 10G',
    storageType: 'NVMe SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Amsterdam', 'Los Angeles', 'Stockholm', 'Tokyo'],
    locationsCN: ['荷兰阿姆斯特丹', '美国洛杉矶', '瑞典斯德哥尔摩', '日本东京'],
    routes: ['普通国际'],
    tags: ['全球多节点', 'NVMe', '稳定'],
    website: 'https://cloud.hosthatch.com/',
    latency: {
      'Amsterdam': { telecom: 180, unicom: 175, mobile: 195 },
      'Los Angeles': { telecom: 168, unicom: 162, mobile: 185 },
      'Stockholm': { telecom: 200, unicom: 195, mobile: 215 },
      'Tokyo': { telecom: 108, unicom: 102, mobile: 85 },
    },
    review: '全球多节点可选，NVMe 高性能硬盘',
    scenarios: ['hosting', 'dev', 'pt'],
    proxyFriendly: false,
    ipPolicy: '工单申请',
    virtualization: 'KVM',

    streaming: '未测试',
  },
  {
    id: 'lisa',
    name: 'LisaHost',
    logo: '/logos/lisa.svg',
    priceFrom: '$4.99/月',
    minConfig: '1C 1G 15G',
    storageType: 'NVMe SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Hong Kong', 'Tokyo'],
    locationsCN: ['中国香港', '日本东京'],
    routes: ['CN2 GIA', 'CMI'],
    tags: ['CN2 GIA', '香港', '精品'],
    website: 'https://lisahost.com/',
    latency: {
      'Hong Kong': { telecom: 35, unicom: 40, mobile: 28 },
      'Tokyo': { telecom: 55, unicom: 60, mobile: 45 },
    },
    review: '专注于香港 CN2 GIA，延迟极低',
    scenarios: ['proxy', 'gaming'],
    proxyFriendly: true,
    ipPolicy: '免费更换',
    virtualization: 'KVM',

    streaming: 'Netflix, Disney+',
  },
  {
    id: 'racknerd',
    name: 'RackNerd',
    logo: '/logos/racknerd.svg',
    priceFrom: '$3/月',
    minConfig: '1C 512M 15G',
    storageType: 'SSD',
    traffic: '2 TB',
    portSpeed: '1Gbps',
    locations: ['Los Angeles', 'Dallas', 'Chicago', 'New York'],
    locationsCN: ['美国洛杉矶', '美国达拉斯', '美国芝加哥', '美国纽约'],
    routes: ['普通国际'],
    tags: ['超低价', '大流量'],
    website: 'https://my.racknerd.com/',
    latency: {
      'Los Angeles': { telecom: 175, unicom: 168, mobile: 192 },
      'Dallas': { telecom: 210, unicom: 205, mobile: 225 },
      'Chicago': { telecom: 225, unicom: 218, mobile: 240 },
      'New York': { telecom: 240, unicom: 235, mobile: 258 },
    },
    review: '极致低价，经常有节日促销',
    scenarios: ['hosting', 'learning', 'pt'],
    proxyFriendly: false,
    ipPolicy: '付费 $3/次',
    virtualization: 'KVM',

    streaming: '未测试',
  },
  {
    id: 'virmach',
    name: 'VirMach',
    logo: '/logos/virmach.svg',
    priceFrom: '$1.00/月',
    minConfig: '1C 256M 10G',
    storageType: 'SSD',
    traffic: '500 GB',
    portSpeed: '1Gbps',
    locations: ['Los Angeles', 'Dallas', 'Chicago', 'Phoenix', 'Amsterdam'],
    locationsCN: ['美国洛杉矶', '美国达拉斯', '美国芝加哥', '美国凤凰城', '荷兰阿姆斯特丹'],
    routes: ['普通国际'],
    tags: ['极致低价', '练手', '黑五神价'],
    website: 'https://billing.virmach.com/',
    latency: {
      'Los Angeles': { telecom: 178, unicom: 172, mobile: 195 },
      'Dallas': { telecom: 215, unicom: 208, mobile: 228 },
      'Chicago': { telecom: 228, unicom: 220, mobile: 242 },
      'Phoenix': { telecom: 185, unicom: 178, mobile: 200 },
      'Amsterdam': { telecom: 195, unicom: 190, mobile: 210 },
    },
    review: '极致低价，黑五常有 $1/月神机',
    scenarios: ['learning'],
    proxyFriendly: false,
    ipPolicy: '付费更换',
    virtualization: 'KVM',

    streaming: '未测试',
  },
  {
    id: 'vps',
    name: 'V.PS',
    logo: '/logos/vps.svg',
    priceFrom: '$5.99/月',
    minConfig: '1C 1G 20G',
    storageType: 'NVMe SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Tokyo', 'Hong Kong', 'Singapore', 'London'],
    locationsCN: ['日本东京', '中国香港', '新加坡', '英国伦敦'],
    routes: ['CN2 GIA', 'AS9929', 'CMI'],
    tags: ['三网优化', '亚太节点', 'NVMe'],
    website: 'https://v.ps/',
    latency: {
      'Tokyo': { telecom: 95, unicom: 88, mobile: 72 },
      'Hong Kong': { telecom: 38, unicom: 42, mobile: 30 },
      'Singapore': { telecom: 88, unicom: 82, mobile: 65 },
      'London': { telecom: 210, unicom: 205, mobile: 228 },
    },
    review: '三网回程优化，亚太节点丰富',
    scenarios: ['proxy', 'gaming'],
    proxyFriendly: true,
    ipPolicy: '免费更换',
    virtualization: 'KVM',

    streaming: 'Netflix, Disney+',
  },
  {
    id: 'vultr',
    name: 'Vultr',
    logo: '/logos/vultr.svg',
    priceFrom: '$2.50/月',
    minConfig: '1C 512M 10G',
    storageType: 'NVMe SSD',
    traffic: '500 GB',
    portSpeed: '1Gbps',
    locations: ['Tokyo', 'Singapore', 'Los Angeles', 'Seoul', 'London', 'Amsterdam', 'Frankfurt'],
    locationsCN: ['日本东京', '新加坡', '美国洛杉矶', '韩国首尔', '英国伦敦', '荷兰阿姆斯特丹', '德国法兰克福'],
    routes: ['普通国际'],
    tags: ['全球多节点', '按小时', 'API友好'],
    website: 'https://vultr.com/',
    latency: {
      'Tokyo': { telecom: 105, unicom: 98, mobile: 82 },
      'Singapore': { telecom: 90, unicom: 85, mobile: 68 },
      'Los Angeles': { telecom: 168, unicom: 162, mobile: 185 },
      'Seoul': { telecom: 78, unicom: 72, mobile: 58 },
      'London': { telecom: 195, unicom: 190, mobile: 210 },
      'Amsterdam': { telecom: 185, unicom: 178, mobile: 200 },
      'Frankfurt': { telecom: 192, unicom: 185, mobile: 205 },
    },
    review: '全球 30+ 节点，按小时灵活计费',
    scenarios: ['dev', 'hosting', 'proxy'],
    proxyFriendly: true,
    ipPolicy: '销毁重建',
    virtualization: 'KVM',

    streaming: '未测试',
  },
  {
    id: 'webhorizon',
    name: 'WebHorizon',
    logo: '/logos/webhorizon.svg',
    priceFrom: '$3.99/月',
    minConfig: '1C 1G 20G',
    storageType: 'NVMe SSD',
    traffic: '2 TB',
    portSpeed: '1Gbps',
    locations: ['Singapore', 'Tokyo', 'London', 'Amsterdam', 'New York'],
    locationsCN: ['新加坡', '日本东京', '英国伦敦', '荷兰阿姆斯特丹', '美国纽约'],
    routes: ['普通国际'],
    tags: ['全球', 'NVMe', 'NAT可选'],
    website: 'https://webhorizon.in/',
    latency: {
      'Singapore': { telecom: 88, unicom: 82, mobile: 65 },
      'Tokyo': { telecom: 105, unicom: 100, mobile: 82 },
      'London': { telecom: 195, unicom: 190, mobile: 210 },
      'Amsterdam': { telecom: 188, unicom: 182, mobile: 202 },
      'New York': { telecom: 240, unicom: 235, mobile: 258 },
    },
    review: '全球多节点，NAT VPS 价格有优势',
    scenarios: ['dev', 'learning'],
    proxyFriendly: true,
    ipPolicy: '工单申请',
    virtualization: 'KVM',

    streaming: '未测试',
  },
  {
    id: 'yxvm',
    name: 'YxVM',
    logo: '/logos/yxvm.svg',
    priceFrom: '$3.50/月',
    minConfig: '1C 1G 15G',
    storageType: 'SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Hong Kong', 'Tokyo', 'Singapore'],
    locationsCN: ['中国香港', '日本东京', '新加坡'],
    routes: ['CMI', '优化线路'],
    tags: ['性价比', '亚太', '香港'],
    website: 'https://yxvm.com/',
    latency: {
      'Hong Kong': { telecom: 45, unicom: 48, mobile: 35 },
      'Tokyo': { telecom: 65, unicom: 70, mobile: 55 },
      'Singapore': { telecom: 92, unicom: 88, mobile: 70 },
    },
    review: '香港性价比商家，非精品线路但价格低',
    scenarios: ['learning', 'proxy'],
    proxyFriendly: true,
    ipPolicy: '工单申请',
    virtualization: 'KVM',

    streaming: 'Netflix',
  },
  {
    id: 'zgovps',
    name: 'ZgoVPS',
    logo: '/logos/zgovps.svg',
    priceFrom: '$4.99/月',
    minConfig: '1C 1G 20G',
    storageType: 'NVMe SSD',
    traffic: '1 TB',
    portSpeed: '1Gbps',
    locations: ['Los Angeles', 'Seattle'],
    locationsCN: ['美国洛杉矶', '美国西雅图'],
    routes: ['CN2 GIA', 'AS4837'],
    tags: ['CN2 GIA', '美西', '性价比'],
    website: 'https://zgovps.com/',
    latency: {
      'Los Angeles': { telecom: 148, unicom: 155, mobile: 172 },
      'Seattle': { telecom: 152, unicom: 158, mobile: 175 },
    },
    review: '美西 CN2 GIA 性价比商家',
    scenarios: ['proxy'],
    proxyFriendly: true,
    ipPolicy: '工单申请',
    virtualization: 'KVM',

    streaming: 'Netflix',
  },
];

/**
 * Affiliate 推广链接重定向映射
 * key: provider id (同 goSlug)
 * value: 实际 affiliate 链接
 * 所有链接通过 /go/:slug → 302 跳转，不直接暴露 affiliate URL
 */
export const AFFILIATE_REDIRECTS: Record<string, string> = {
  dmit: 'https://www.dmit.io/aff.php?aff=6460',
  bandwagon: 'https://bwh81.net/aff.php?aff=70788',
  racknerd: 'https://my.racknerd.com/aff.php?aff=7586',
  cloudcone: 'https://app.cloudcone.com/?ref=9528',
  buyvm: 'https://my.frantech.ca/aff.php?aff=6497',
  hosthatch: 'https://cloud.hosthatch.com/a/5546',
  vultr: 'https://www.vultr.com/?ref=9909229',
  digitalocean: 'https://m.do.co/c/3ed588d4a2f9',
  vps: 'https://vps.hosting/?affid=2394',
  lisa: 'https://lisahost.com/aff.php?aff=12102',
  cloudsilk: 'https://cloudsilk.io/aff.php?aff=946',
  colocrossing: 'https://cloud.colocrossing.com/aff.php?aff=2001',
  gigsgigs: 'https://clientarea.gigsgigscloud.com/?affid=4183',
  hostdare: 'https://bill.hostdare.com/aff.php?aff=4654',
  webhorizon: 'https://clients.webhorizon.net/?affid=232',
  yxvm: 'https://yxvm.com/aff.php?aff=913',
  zgovps: 'https://clients.zgovps.com/?affid=1645',
  virmach: 'https://billing.virmach.com/',
};
